export const metadata = {
  title: "Laca",
  description: "Generated by lonelyman",
};
import Navbar from "./components/Navbar/Navbar";
import "./globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <div className="w-1/4">
            <Navbar />
          </div>
          <div className="w-3/4 p-6">{children}</div>
        </div>
      </body>
    </html>
  );
}
